### 获取当前用户余额信息
GET http://127.0.0.1:9001/imooc/ecommerce-account-service/balance/currentBalance
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjExLFwidXNlcm5hbWVcIjpcInRlc3QyXCJ9IiwianRpIjoiYmI4OTgzMjYtMjZjNC00MjFjLTlhY2UtNTJlYzU4NjdhOTE1IiwiZXhwIjoxNjU1NjU0NDAwfQ.CEDONYb80SE09BcZoRRkOgscO4YXtPYncSyu4gJkbHi_XhZi4AJzBWUA339zBzGQosfd8XlmhlZpV3ni9xq7jIfQx0Q-RmaedcT1Hv7KFrUPc8E0827UHcydiOYU7LDe-z424F7YmVEqV948lPE3TbAYjBj5FKpqDTEWOsBcjnI2Jf6tfQbUP4gS_0q69xGdJGDCHexmMWyuWMsu6EFwuXgxmeMUNAEY0nXF0OsxDD9HAPbXjlstwLd20pwNhuYbue9VCXI7y6ddDrfH4okd8Z8LfvGyuxHZWKmX7NARNp-tfFSJF_E5zFvBvvWWDxaKHjof3SVckYrjPFvXeBQyxQ


### 扣减余额
PUT http://127.0.0.1:9001/imooc/ecommerce-account-service/balance/deductBalance
Content-Type: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjExLFwidXNlcm5hbWVcIjpcInRlc3QyXCJ9IiwianRpIjoiYmI4OTgzMjYtMjZjNC00MjFjLTlhY2UtNTJlYzU4NjdhOTE1IiwiZXhwIjoxNjU1NjU0NDAwfQ.CEDONYb80SE09BcZoRRkOgscO4YXtPYncSyu4gJkbHi_XhZi4AJzBWUA339zBzGQosfd8XlmhlZpV3ni9xq7jIfQx0Q-RmaedcT1Hv7KFrUPc8E0827UHcydiOYU7LDe-z424F7YmVEqV948lPE3TbAYjBj5FKpqDTEWOsBcjnI2Jf6tfQbUP4gS_0q69xGdJGDCHexmMWyuWMsu6EFwuXgxmeMUNAEY0nXF0OsxDD9HAPbXjlstwLd20pwNhuYbue9VCXI7y6ddDrfH4okd8Z8LfvGyuxHZWKmX7NARNp-tfFSJF_E5zFvBvvWWDxaKHjof3SVckYrjPFvXeBQyxQ

{
  "userId": 11,
  "balance": 2000
}