### 查询nacos中的服务
GET http://127.0.0.1:9001/imooc/ecommerce-nacos-client/nacos-client/service-instance?serviceId=e-commerce-gateway
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcInRlc3QxXCJ9IiwianRpIjoiYmQxNWIxNWUtMjExMC00MGEyLTk0ZmUtMWUzYmE2YTk0MmU5IiwiZXhwIjoxNjU1MDQ5NjAwfQ.DucyePlBucs7Cf7Y0wgyCNLl_epTqaEmX1zvhV7d5qkMQwDygnl4dZ0MizROheiUO4jEylKRsxsjNhkM9KZi6xoPBzEa1GaCOU8VrvT3PdFaKryGBbv7rrVPrbmyY6vMvzm-m0mfBW6QnAr65Muv_ENDz5x5esuBr0e3QzSfGnEbMh3hU_ipNM4qMY9wO8Ydku5L-BkTALajzdo8GlXx1GM6M3lRiH57z0OyOBSAsDNv3rrVlYVLdZfjRNJL61PcXp9AoLfKvvJrbOp5Vk7XuoJWeXAU1CtOwPViNOs21JY7NuZVk6fIoE_0eQ2ywF2aPq-a1mynr7v4F23tGdGb4A
token: imooc

